export class Reponse {
    _id?: string;
    nom?: string;
    genre?: string;
    age?: number;
    etat?: string;
    emploi?: string;
    securite?: number;
    object1?: number;
    object2?: number;
    object3?: number;
    object4?: number;
    object5?: number;
    object6?: number;
    object7?: number;
    invest1?: number;
    invest2?: number;
    invest3?: number;
    invest4?: number;
    invest5?: number;
    invest6?: number;
    invest7?: number;
    // horizon?: number;
    // tolerance1?: number;
    // tolerance2?: number;
    // tolerance3?: number;
    // tolerance4?: number;
    // renseignement1?: number;
    // renseignement2?: boolean[];
    // renseignement22?: number;
    // renseignement3?: number;
    // minrendement?: number;
    // maxpert?: number;
    created?: Date;
    score?: number;
    profil?: string;
    montant?: number;
}
